### ISSUE TITLE
Help Needed wrt to Mysql

### ISSUE THREAD

**Issue by zpratikpathak** [flexform-dev/flexform-server#12]
would you please tell me  sample env with mySQL database?

I'm using DATABASE_URL="mysql://username:password@host:port/database_name"
but it's giving error
```
[critical] Error thrown while running command "doctrine:migrations:migrate". Message: "Malformed parameter "url"."
```

thankyou

**Comment by sdkfuyr** [comment]
Hello!

It is hard to tell without seeing the full mysql connection string.
I can guess there is a symbol like "#" in the password that brakes URL:

For example: # sign is not recognized by PHP's parse_url() function as valid, this issue is not related to Symfony, but to Doctrine DBAL
